version: '3.7'

services:
  tomcat:
    container_name: jsf-app
    environment: 
      - PORT=6969
    build:
      context: .
      dockerfile: Dockerfile
    image: luqmansen/jsf-ugly
    volumes:
      - './target/:/home/webapps/'
#      - './src/main/webapp/:/home/webapps/ROOT'
    ports:
    - "8080:6969"

  mariadb:
    container_name: maridb-jsf
    image: yobasystems/alpine-mariadb:10.4.13
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    volumes:
      - jsf-mariadb:/var/lib/mysql/data:rw
      - ./mysql-dump/student.sql:/docker-entrypoint-initdb.d/student.sql:ro

volumes:
  jsf-mariadb: